import os

from os import listdir
from os.path import isfile, join


for f in listdir("./"):
    splits = f.split(".")
    if len(splits) > 1:
	if (isfile(join("./", f)) and splits[1] == "cc"):
            env = Environment()
            env.Append(CC="clang++")
            env.Append(CCFLAGS ="-pthread -DELOG -g")
            env.Append(LIBS = ["pthread"])
            env.Program(splits[0], [f])

