import os

from os import listdir
from os.path import isfile, join

env = Environment()
env.Append(CC="clang++")
env.Append(CCFLAGS =["-pthread", "-DELOG"])
env.Append(LIBS = ["pthread"])

files = []
for f in listdir("./"):
    splits = f.split(".")
    if len(splits) > 1:
	if (isfile(join("./", f)) and splits[1] == "cc"):
	    files.append(f)
print(files)
env.Program(files)

